# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57a3b2a04f71d8d6885d42b9ed5ce78fa5c05f593b9444f62472b26f3660f1e4923ab28769b5127f842dc5d0d4955ae6c2a836252c5dac299421fa1545383ae2

test:
  secret_key_base: cc5ee6d512de0945e8cfbdf900edebef9fa8dfde6b8ffb2ce7c04e41eb847ffa4c5d44ba2ddf1ac49ca9d952f79912f93871619d79bc3e5b396a30968407a176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
